name: Build Artifact

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install thrift
        uses: valitydev/action-setup-thrift@v0.0.1
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Retrieve commit number
        run: |
          echo "::set-output name=COMMIT_NUMBER::$(git rev-list HEAD --count)"
        id: commit_number
      - name: Retrieve short sha
        run: |
          echo "::set-output name=SHA_7::${GITHUB_SHA::7}"
        id: short_sha
      - name: Build package
        run: mvn --batch-mode -Dcommit.number=${{ steps.commit_number.outputs.COMMIT_NUMBER }} -DnewVersion="1.${{ steps.commit_number.outputs.COMMIT_NUMBER }}-${{ steps.short_sha.outputs.SHA_7 }}" clean compile -f pom.xml
