name: Build Artifact

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Install thrift
        uses: valitydev/action-setup-thrift@v0.0.1
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'
      - name: Retrieve commit info
        run: |
          echo "::set-output name=COMMIT_NUMBER::$(git rev-list HEAD --count)"
          echo "::set-output name=SHA_7::${GITHUB_SHA::7}"
        id: commit_info
      - name: Build package
        run: |
          mvn --no-transfer-progress --batch-mode -Dcommit.number=${{ steps.commit_info.outputs.COMMIT_NUMBER }} versions:set versions:commit -DnewVersion=1.${{ steps.commit_info.outputs.COMMIT_NUMBER }}-${{ steps.commit_info.outputs.SHA_7 }} && \
          mvn --batch-mode -Dcommit.number=${{ steps.commit_info.outputs.COMMIT_NUMBER }} compile -f pom.xml
