name: Build Artifact

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: setup-binary
        uses: supplypike/setup-bin@v1
        with:
          uri: 'https://github.com/valitydev/thrift/releases/download/0.14.2/thrift-0.14.2-linux-x86_64.tar.gz'
          name: 'thrift'
          version: '0.14.2'
          command: tar -xvf thrift-0.14.2-darwin-arm64.tar.gz
