name: Build Artifact

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup thrift
        uses: supplypike/setup-bin@v1
        with:
          uri: 'https://github.com/valitydev/thrift/releases/download/0.14.2/thrift-0.14.2-linux-x86_64.tar.gz'
          name: 'thrift'
          version: '0.14.2'
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up Maven
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Retrieve commit number
        run: |
          echo "::set-output name=COMMIT_NUMBER::$(git rev-list HEAD --count)"
        id: commit_number
      - name: Retrieve short sha
        run: |
          echo "::set-output name=SHA_7::${GITHUB_SHA::7}"
        id: short_sha
      - name: Build package
        run: mvn --batch-mode -Dcommit.number=${{ steps.commit_number.outputs.COMMIT_NUMBER }} -DnewVersion="1.${{ steps.commit_number.outputs.COMMIT_NUMBER }}-${{ steps.short_sha.outputs.SHA_7 }}" clean compile -f pom.xml
