name: Build Artifact

on:
  push:
    branches:
      - 'master'
      - 'main'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup thrift
        uses: supplypike/setup-bin@v1
        with:
          uri: 'https://github.com/valitydev/thrift/releases/download/0.14.2/thrift-0.14.2-linux-x86_64.tar.gz'
          name: 'thrift'
          version: '0.14.2'
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Install gpg secret key
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - name: Retrieve commit number
        run: |
          echo "::set-output name=COMMIT_NUMBER::$(git rev-list HEAD --count)"
        id: commit_number
      - name: Publish package
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        run: |
          mvn \
            --no-transfer-progress \
            --batch-mode \
            -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} \
            -Dcommit.number=${{ steps.commit_number.outputs.COMMIT_NUMBER }} \
            -DnewVersion="1.${{ steps.commit_number.outputs.COMMIT_NUMBER }}-${{ GITHUB_SHA::7 }}" \
            clean deploy -f pom.xml -Pdeploy