name: Deploy Artifact

on:
  push:
    branches:
      - 'master'
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Retrieve commit number
        run: |
          echo "::set-output name=COMMIT_NUMBER::$(git rev-list HEAD --count)"
        id: commit_number
      - name: Retrieve short sha
        run: |
          echo "::set-output name=SHA_7::${GITHUB_SHA::7}"
        id: short_sha

      - name: Deploy package
        uses: valitydev/action-deploy-jdk-package@v1.0.9
        with:
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_TOKEN }}
          deploy-secret-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          deploy-secret-key-password: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
          thrift-install: 'true'
          maven-custom-parameters: '-Dcommit.number=${{ steps.commit_number.outputs.COMMIT_NUMBER }} -DnewVersion="1.${{ steps.commit_number.outputs.COMMIT_NUMBER }}-${{ steps.short_sha.outputs.SHA_7 }}"'