name: Java build

on:
  pull_request:
    branches:
      - "*"

permissions:
  contents: read

jobs:
  build:
    with:
      java-version: 21
    uses: valitydev/java-workflow/.github/workflows/maven-thrift-build.yml@v3